clear all; close all; clc;

load('data.mat');

[pitch_EKF_right_thigh, pitch_EKF_right_shank] = ...
            fusion_EKF(g_Y_right_thigh_1_C', ...
                       g_Y_right_shank_1_C', ...
                       a_X_right_thigh_1_C', ...
                       a_Z_right_thigh_1_C', ...
                       a_X_right_shank_1_C', ...
                       a_Z_right_shank_1_C', ...
                       f, 0.5, 0.5);
                   
n = 500;

figure1 = figure(1);
clf;
set(figure1, 'defaulttextinterpreter', 'latex');
hold on
plot(time(1:n), pitch_acc_right_shank(1:n), ...
     time(1:n), pitch_gyro_right_shank(1:n), ...
     time(1:n), pitch_KF_right_shank(1:n), ...
     time(1:n), pitch_GKF_right_shank(1:n), ...
     time(1:n), pitch_EKF_right_shank(1:n));
title('Pitch angle of the right shank - Comparison');
xlabel('Time in seconds');
ylabel('Pitch angle in degrees');
legend('Accelerometer-based', ...
       'Integration of angular rate', ...
       'Kalman filter', 'Gated Kalman filter', ...
       'Extended Kalman filter');
   
matlab2tikz('../images/experiment_1.tikz', 'height', ...
            '\figureheight', 'width', '\figurewidth');
   
   