clear all; close all; clc;

load('data.mat');

[pitch_EKF_right_thigh, pitch_EKF_right_shank] = ...
            fusion_EKF(g_Y_right_thigh_1_C', ...
                       g_Y_right_shank_1_C', ...
                       a_X_right_thigh_1_C', ...
                       a_Z_right_thigh_1_C', ...
                       a_X_right_shank_1_C', ...
                       a_Z_right_shank_1_C', ...
                       f, 0.5, 0.5);

figure();
hold on
plot(time, pitch_acc_right_shank, ...
     time, pitch_gyro_right_shank, ...
     time, pitch_KF_right_shank, ...
     time, pitch_GKF_right_shank, ...
     time, pitch_EKF_right_shank);
title('Pitch angle of the right shank - Comparison');
xlabel('Time in seconds');
ylabel('Pitch in degrees');
legend('Accelerometer-based', ...
       'Integration of angular rate', ...
       'Kalman filter', 'Gated Kalman filter', ...
       'Extended Kalman filter');
   
   
   
   
   