data_struct={1,     'time',  '',       '',  '    ',     1;
             2,     'p',    '1',  'right',  'foot',     1;
             3,     'p',    '2',  'right',  'foot',     1;
             4,     'p',    '3',  'right',  'foot',     1;
             5,     'p',    '4',  'right',  'foot',     1;
             6,     'g',    'Y',  'right',  'foot',     1;
             7,     'g',    'X',  'right',  'foot',     1;
             8,     'g',    'Z',  'right',  'foot',     -1;
             9,     'a',    'Y',  'right',  'foot',     -1;
             10,    'a',    'X',  'right',  'foot',     -1;
             11,    'a',    'Z',  'right',  'foot',     1;
             12,    'h',    'Y',  'right',  'foot',     1;
             13,    'h',    'X',  'right',  'foot',     1;
             14,    'h',    'Z',  'right',  'foot',     1; 
             15,    'p',    '1',  'left',   'foot',     1;
             16,    'p',    '2',  'left',   'foot',     1; 
             17,    'p',    '3',  'left',   'foot',     1;
             18,    'p',    '4',  'left',   'foot',     1;
             19,    'g',    'Y',  'left',   'foot',     -1;
             20,    'g',    'X',  'left',   'foot',     -1;
             21,    'g',    'Z',  'left',   'foot',     -1;
             22,    'a',    'Y',  'left',   'foot',     1;
             23,    'a',    'X',  'left',   'foot',     1;
             24,    'a',    'Z',  'left',   'foot',     1;
             25,    'h',    'Y',  'left',   'foot',     1;
             26,    'h',    'X',  'left',   'foot',     1;
             27,    'h',    'Z',  'left',   'foot',     1;
             };