This is makeindex, version 2.15 [TeX Live 2014] (kpathsea + Thai support).
Scanning style file /Users/Rob/Documents/APA/Documents/Bachelor's Thesis Rob/main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/Rob/Documents/APA/Documents/Bachelor's Thesis Rob/main.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file /Users/Rob/Documents/APA/Documents/Bachelor's Thesis Rob/main.acr....done (6 lines written, 0 warnings).
Output written in /Users/Rob/Documents/APA/Documents/Bachelor's Thesis Rob/main.acr.
Transcript written in /Users/Rob/Documents/APA/Documents/Bachelor's Thesis Rob/main.alg.
