This is makeindex, version 2.15 [TeX Live 2014] (kpathsea + Thai support).
Scanning style file /Users/Rob/Documents/APA/Documents/Bachelor Thesis Rob/.texpadtmp/main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/Rob/Documents/APA/Documents/Bachelor Thesis Rob/.texpadtmp/main.acn....done (13 entries accepted, 0 rejected).
Sorting entries....done (44 comparisons).
Generating output file /Users/Rob/Documents/APA/Documents/Bachelor Thesis Rob/.texpadtmp/main.acr....done (24 lines written, 0 warnings).
Output written in /Users/Rob/Documents/APA/Documents/Bachelor Thesis Rob/.texpadtmp/main.acr.
Transcript written in /Users/Rob/Documents/APA/Documents/Bachelor Thesis Rob/.texpadtmp/main.alg.
